version: "3"
services:
  app:
      container_name: wedev-org
      image: node:alpine
      volumes:
        - ./:/app
      working_dir: /app
      environment:
        NODE_ENV: production
        VIRTUAL_HOST: www.wedev.org
        VIRTUAL_PORT: 3005
        LETSENCRYPT_HOST: www.wedev.org
        LETSENCRYPT_EMAIL: arancibiajav@gmail.com
        PORT: 3005
      ports:
        - 3005
      command: npm run start
networks:
  default:
    external:
      name: webproxy

